import { StyleSheet } from 'react-native';
import { Radius } from '@/presentation/styles/global-styles';

export const styles = StyleSheet.create({
  cardContainer: {
    marginVertical: 10,
    borderRadius: Radius.big,
    borderWidth: 1,
    borderColor: 'rgba(40, 209, 195, 0.15)',
    overflow: 'visible',
    elevation: 10,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
  },
  pressableArea: {
    borderRadius: Radius.big,
    overflow: 'hidden',
  },
  gradientBg: {
    padding: 16,
    borderRadius: Radius.big,
  },
  shimmerEffect: {
    position: 'absolute',
    top: -120,
    left: 0,
    width: 250,
    height: 600,
    zIndex: 1,
    opacity: 0.5,
  },
  glowBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: Radius.big,
    borderWidth: 1.5,
    opacity: 0.25,
  },
  badgeSkew: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 3,
    backgroundColor: '#070a1e',
    borderColor: '#192147',
    borderWidth: 1.5,
    borderRadius: 6,
    transform: [{ skewX: '-12deg' }],
    marginBottom: 12,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#00c897',
    letterSpacing: 1.5,
    transform: [{ skewX: '12deg' }],
  },
  cardMain: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    zIndex: 2,
  },
  logoFrame: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(10, 15, 45, 0.6)',
    borderWidth: 2,
    borderColor: 'rgba(0, 200, 151, 0.3)',
    shadowColor: '#00c897',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  logoImage: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
  },
  infoContainer: {
    flex: 1,
    marginLeft: 16,
    justifyContent: 'center',
  },
  brandName: {
    fontSize: 20,
    fontWeight: '900',
    color: 'white',
    letterSpacing: 0.5,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  statusWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(7, 10, 30, 0.5)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radius.small,
    borderWidth: 1,
  },
  statusIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 6,
  },
  statusLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 1.5,
  },
  favIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  divider: {
    height: 1.5,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    marginVertical: 14,
  },
  techPanel: {
    flexDirection: 'row',
    backgroundColor: '#0a0f26',
    borderRadius: Radius.medium,
    padding: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(40, 209, 195, 0.25)',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 2,
  },
  techPanelLeft: {
    flex: 1.3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: 10,
    gap: 16,
  },
  techLabelValue: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 2,
  },
  techLabel: {
    fontSize: 11,
    color: '#CFD8E9',
    fontWeight: '700',
    letterSpacing: 1.2,
  },
  techValue: {
    fontSize: 17,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  techPanelRight: {
    flex: 0.7,
    alignItems: 'flex-end',
    gap: 8,
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(255, 255, 255, 0.08)',
    paddingLeft: 14,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(251, 191, 36, 0.1)',
    borderColor: 'rgba(251, 191, 36, 0.3)',
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    gap: 4,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FBBF24',
  },
  barcodeContainer: {
    flexDirection: 'row',
    gap: 2,
    marginTop: 4,
    opacity: 0.4,
  },
  barcodeLine: {
    backgroundColor: '#6E7C96',
    borderRadius: 1,
  },
  actionFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 14,
    gap: 6,
    zIndex: 2,
  },
  actionText: {
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 1.5,
  },
});
